#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL (signal 9)

# Find PID(s) of the 7-highlander process
pids=$(pgrep -f "7-highlander")

# Kill each PID using SIGKILL
for pid in $pids; do
    kill -9 "$pid"
done
